"use strict";

// Adds only fixed public catalog/community content to Production. The stable IDs
// and create-only writes make repeated runs safe and preserve later admin edits.
const fs = require("node:fs");
const path = require("node:path");
const { initializeApp, cert, deleteApp } = require("firebase-admin/app");
const { getFirestore, Timestamp } = require("firebase-admin/firestore");

const TARGET_PROJECT = "homeplant-production";
const confirm = `--confirm-project=${TARGET_PROJECT}`;
const at = value => Timestamp.fromDate(new Date(value));

const documents = [
  ["community_posts", "homeplant-tip-watering-2026", {postId:"homeplant-tip-watering-2026",authorId:"homeplant-editorial",authorName:"Đội ngũ HomePlant",authorAvatar:"",content:"Mẹo tưới cây: hãy kiểm tra 2–3 cm đất mặt trước khi tưới. Nếu đất vẫn còn ẩm, chờ thêm một ngày sẽ an toàn hơn là tưới theo lịch cứng.",images:[],likeCount:28,commentCount:6,status:"active",createdAt:at("2026-09-19T02:00:00Z")}],
  ["community_posts", "homeplant-tip-light-2026", {postId:"homeplant-tip-light-2026",authorId:"homeplant-editorial",authorName:"Đội ngũ HomePlant",authorAvatar:"",content:"Lá cây nghiêng hẳn về phía cửa sổ là dấu hiệu cây đang tìm sáng. Xoay chậu một phần tư vòng mỗi tuần để tán cây phát triển cân đối hơn.",images:[],likeCount:34,commentCount:4,status:"active",createdAt:at("2026-09-20T02:00:00Z")}],
  ["community_posts", "homeplant-tip-yellow-leaves-2026", {postId:"homeplant-tip-yellow-leaves-2026",authorId:"homeplant-editorial",authorName:"Đội ngũ HomePlant",authorAvatar:"",content:"Một lá già vàng tự nhiên không đáng lo. Nhưng nếu nhiều lá vàng cùng lúc, hãy kiểm tra úng nước, độ thoáng của giá thể và ánh sáng trước khi bón thêm phân.",images:[],likeCount:41,commentCount:9,status:"active",createdAt:at("2026-09-21T02:00:00Z")}],
  ["community_posts", "homeplant-tip-clean-leaves-2026", {postId:"homeplant-tip-clean-leaves-2026",authorId:"homeplant-editorial",authorName:"Đội ngũ HomePlant",authorAvatar:"",content:"Cuối tuần xanh: dùng khăn mềm ẩm lau hai mặt lá. Lá sạch quang hợp tốt hơn, đồng thời bạn có thể phát hiện sớm rệp sáp và nhện đỏ.",images:[],likeCount:52,commentCount:11,status:"active",createdAt:at("2026-09-22T02:00:00Z")}],
  ["sample_plants", "golden-pothos", {name:"Trầu Bà Vàng",scientificName:"Epipremnum aureum",description:"Cây dây leo dễ chăm, nổi bật với lá xanh pha vàng và phù hợp cho người mới bắt đầu.",imageUrl:"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9d/Epipremnum_aureum_31082012.jpg/960px-Epipremnum_aureum_31082012.jpg",createdAt:at("2026-09-22T03:00:00Z"),care:{light:"Ánh sáng gián tiếp từ trung bình đến sáng; tránh nắng gắt.",water:"Tưới khi 2–3 cm đất mặt đã khô.",soil:"Giá thể tơi xốp, thoát nước tốt.",fertilizer:"Bón phân loãng mỗi 4–6 tuần trong mùa sinh trưởng."},diseases:[{issue:"Lá vàng",cause:"Tưới quá nhiều hoặc thoát nước kém.",treatment:"Để đất khô hơn giữa hai lần tưới và kiểm tra lỗ thoát nước."}]}],
  ["sample_plants", "zz-plant", {name:"Kim Tiền",scientificName:"Zamioculcas zamiifolia",description:"Cây nội thất bền bỉ, chịu thiếu sáng và có thân lá xanh bóng, thích hợp cho văn phòng.",imageUrl:"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b9/Zamioculcas_zamiifolia_Chameleon_1.jpg/960px-Zamioculcas_zamiifolia_Chameleon_1.jpg",createdAt:at("2026-09-22T03:01:00Z"),care:{light:"Chịu sáng yếu nhưng phát triển tốt nhất ở ánh sáng gián tiếp.",water:"Chỉ tưới khi phần lớn giá thể đã khô.",soil:"Đất thoát nước nhanh, có perlite hoặc đá bọt.",fertilizer:"Bón nhẹ mỗi 6–8 tuần vào mùa ấm."},diseases:[{issue:"Thân mềm, lá vàng",cause:"Úng nước gây thối củ.",treatment:"Ngừng tưới, cắt phần thối và thay giá thể khô thoáng."}]}],
  ["sample_plants", "peace-lily", {name:"Lan Ý",scientificName:"Spathiphyllum wallisii",description:"Cây lá xanh đậm với mo hoa trắng thanh lịch, ưa ẩm và ánh sáng dịu trong nhà.",imageUrl:"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a1/Peace_lily_-_2.jpg/960px-Peace_lily_-_2.jpg",createdAt:at("2026-09-22T03:02:00Z"),care:{light:"Ánh sáng gián tiếp; ánh sáng tốt giúp cây ra hoa.",water:"Giữ đất ẩm vừa, tưới khi mặt đất bắt đầu se khô.",soil:"Giá thể giàu hữu cơ nhưng thoát nước tốt.",fertilizer:"Bón phân cân bằng loãng mỗi 6 tuần."},diseases:[{issue:"Đầu lá nâu",cause:"Không khí khô, nước nhiều khoáng hoặc bón phân đậm.",treatment:"Tăng ẩm, dùng nước ít khoáng và giảm nồng độ phân."}]}],
  ["sample_plants", "rubber-plant", {name:"Đa Búp Đỏ",scientificName:"Ficus elastica",description:"Cây thân gỗ trong nhà có lá lớn bóng, tạo điểm nhấn mạnh mẽ cho không gian sống.",imageUrl:"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Gummibaum_%28Ficus_elastica_Robusta%29.jpg/960px-Gummibaum_%28Ficus_elastica_Robusta%29.jpg",createdAt:at("2026-09-22T03:03:00Z"),care:{light:"Ánh sáng gián tiếp mạnh, có thể nhận nắng sớm nhẹ.",water:"Tưới khi 3–5 cm đất mặt khô.",soil:"Đất tơi xốp, giữ ẩm vừa và thoát nước tốt.",fertilizer:"Bón phân mỗi tháng trong mùa sinh trưởng."},diseases:[{issue:"Rụng lá",cause:"Thay đổi môi trường đột ngột, thiếu sáng hoặc úng nước.",treatment:"Ổn định vị trí, điều chỉnh ánh sáng và chu kỳ tưới."}]}],
  ["articles", "GUIDE_WATERING_2026", {title:"Tưới cây đúng cách: đọc đất thay vì nhìn lịch",content:"Tưới nước là việc đơn giản nhưng cũng là nguyên nhân phổ biến nhất khiến cây trong nhà suy yếu. Một lịch cố định chỉ nên dùng để nhắc bạn kiểm tra cây, không phải mệnh lệnh phải tưới.\n\nHãy chạm vào 2–3 cm đất mặt. Nếu đất còn mát và ẩm, cây chưa cần thêm nước. Khi đất đã se khô, tưới chậm quanh bầu cho đến khi nước bắt đầu thoát ra đáy chậu, sau đó đổ bỏ nước đọng trong đĩa.\n\nChậu nhỏ, phòng nóng và nhiều ánh sáng sẽ khô nhanh hơn. Ngược lại, chậu lớn, mùa mưa hoặc phòng điều hòa ít nắng cần khoảng cách tưới dài hơn. Quan sát trọng lượng chậu và độ căng của lá sẽ giúp bạn hiểu nhịp uống nước riêng của từng cây.\n\nDấu hiệu tưới quá nhiều thường là lá vàng mềm, đất có mùi và thân sát gốc nhũn. Thiếu nước thường làm lá rũ nhưng đất khô nhẹ và chậu rất nhẹ. Khi chưa chắc chắn, chờ thêm một ngày thường an toàn hơn là tưới thêm.",coverImage:"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9d/Epipremnum_aureum_31082012.jpg/960px-Epipremnum_aureum_31082012.jpg",tags:["Tưới nước","Cơ bản","Cây trong nhà"],views:0,createdAt:at("2026-09-22T04:00:00Z")}],
  ["articles", "GUIDE_LIGHT_2026", {title:"Chọn vị trí ánh sáng phù hợp cho cây trong nhà",content:"Ánh sáng gián tiếp mạnh là vùng sáng gần cửa sổ nhưng tia nắng không chiếu gắt trực tiếp lên lá trong nhiều giờ. Đây là vị trí phù hợp với phần lớn cây lá nhiệt đới.\n\nCửa sổ hướng đông thường có nắng sáng dịu. Hướng nam và tây có thể rất mạnh, nên dùng rèm mỏng hoặc đặt cây lùi xa kính. Ở vị trí thiếu sáng, cây mọc chậm, khoảng cách giữa các lá dài và tán nghiêng về phía cửa sổ.\n\nBạn nên xoay chậu một phần tư vòng mỗi tuần để tán phát triển cân đối. Không chuyển cây đột ngột từ góc tối ra nắng mạnh; hãy tăng ánh sáng từ từ trong một đến hai tuần để tránh cháy lá.\n\nMàu lá nhạt, mảng cháy khô và nhiệt độ lá cao là dấu hiệu ánh sáng quá mạnh. Khi đó hãy đưa cây lùi khỏi cửa sổ hoặc che nắng vào khung giờ trưa.",coverImage:"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Gummibaum_%28Ficus_elastica_Robusta%29.jpg/960px-Gummibaum_%28Ficus_elastica_Robusta%29.jpg",tags:["Ánh sáng","Vị trí đặt cây","Cơ bản"],views:0,createdAt:at("2026-09-22T04:01:00Z")}],
  ["articles", "GUIDE_REPOTTING_2026", {title:"Khi nào cần thay chậu và cách giảm sốc cho cây",content:"Cây không cần thay chậu chỉ vì đã ở trong chậu một năm. Hãy thay khi rễ mọc kín bầu, chui nhiều qua lỗ thoát nước, đất khô quá nhanh hoặc cây mất cân đối so với chậu.\n\nChọn chậu mới lớn hơn đường kính chậu cũ khoảng 2–5 cm. Chậu quá lớn giữ nhiều nước quanh vùng rễ chưa sử dụng và làm tăng nguy cơ úng. Giá thể mới cần phù hợp với loài cây và luôn có khả năng thoát nước.\n\nTrước khi thay, tưới nhẹ từ hôm trước để bầu không quá khô. Gỡ cây cẩn thận, cắt bỏ rễ đen mềm hoặc có mùi, giữ lại rễ sáng màu và chắc. Đặt cây ở độ cao cũ, lấp giá thể mà không nén quá chặt.\n\nSau khi thay chậu, đặt cây ở nơi sáng dịu, tránh bón phân trong khoảng ba đến bốn tuần. Một vài lá rũ nhẹ là phản ứng bình thường; hãy giữ môi trường ổn định và tránh tưới liên tục vì lo cây bị sốc.",coverImage:"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b5/Aloe_vera_Lanzarote.jpg/960px-Aloe_vera_Lanzarote.jpg",tags:["Thay chậu","Rễ cây","Giá thể"],views:0,createdAt:at("2026-09-22T04:02:00Z")}],
  ["articles", "GUIDE_PESTS_2026", {title:"Phát hiện sớm rệp sáp và nhện đỏ trên cây",content:"Kiểm tra cây mỗi tuần giúp xử lý sâu hại trước khi chúng lan rộng. Hãy quan sát mặt dưới lá, nách lá và các chồi non—đây là nơi rệp sáp, rệp vảy và nhện đỏ thường ẩn náu.\n\nRệp sáp trông như cụm bông trắng nhỏ. Nhện đỏ rất khó thấy nhưng thường để lại chấm vàng li ti và tơ mảnh. Khi phát hiện, cách ly cây khỏi những chậu khác, cắt bỏ phần bị nặng và rửa kỹ cả hai mặt lá.\n\nVới ổ dịch nhẹ, lau côn trùng bằng khăn ẩm và lặp lại kiểm tra sau ba đến năm ngày. Có thể dùng xà phòng diệt côn trùng hoặc sản phẩm chuyên dụng đúng hướng dẫn, thử trước trên một vùng lá nhỏ.\n\nGiữ tán cây thông thoáng, lau bụi định kỳ và tránh bón thừa đạm. Tiếp tục theo dõi ít nhất ba tuần vì trứng có thể nở sau lần xử lý đầu tiên.",coverImage:"https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e2/%D8%A8%D8%B1%DA%AF_%D9%88_%D8%B3%D8%A7%D9%82%D9%87_%DA%AF%DB%8C%D8%A7%D9%87_%D8%B9%D9%86%DA%A9%D8%A8%D9%88%D8%AA%DB%8C_04-Chlorophytum_comosum%2C.jpg/960px-%D8%A8%D8%B1%DA%AF_%D9%88_%D8%B3%D8%A7%D9%82%D9%87_%DA%AF%DB%8C%D8%A7%D9%87_%D8%B9%D9%86%DA%A9%D8%A8%D9%88%D8%AA%DB%8C_04-Chlorophytum_comosum%2C.jpg",tags:["Sâu bệnh","Rệp sáp","Nhện đỏ"],views:0,createdAt:at("2026-09-22T04:03:00Z")}],
];

const additionalPlants = [
  ["monstera-deliciosa", "Trầu Bà Lá Xẻ", "Monstera deliciosa", "Cây nhiệt đới có lá xẻ đặc trưng, phù hợp làm điểm nhấn ở phòng khách có ánh sáng tốt.", "Monstera_deliciosa2.jpg", "Ánh sáng gián tiếp sáng; nắng sớm nhẹ giúp lá xẻ đẹp hơn.", "Tưới khi 3–5 cm đất mặt khô, đổ bỏ nước thừa trong đĩa.", "Giá thể thoáng gồm vỏ thông, xơ dừa và perlite.", "Bón phân cân bằng loãng mỗi 4–6 tuần vào mùa sinh trưởng.", "Mép lá nâu", "Không khí khô, thiếu nước hoặc muối tích tụ.", "Tăng ẩm vừa phải, kiểm tra nhịp tưới và xả muối cho giá thể."],
  ["heartleaf-philodendron", "Trầu Bà Tim", "Philodendron hederaceum", "Cây dây leo lá hình tim, sinh trưởng ổn định và dễ tạo dáng rủ hoặc leo cọc.", "Philodendron_hederaceum_2005-03-14.jpg", "Ánh sáng gián tiếp trung bình đến sáng; tránh nắng trưa.", "Tưới khi 2–3 cm đất mặt khô.", "Đất giàu hữu cơ, thoáng khí và thoát nước tốt.", "Bón phân loãng mỗi tháng vào mùa ấm.", "Lá vàng đồng loạt", "Giá thể giữ nước lâu hoặc rễ thiếu oxy.", "Giãn lần tưới, kiểm tra rễ và thay giá thể thoáng nếu cần."],
  ["chinese-evergreen", "Ngân Hậu", "Aglaonema commutatum", "Cây nội thất có tán lá bạc xanh, chịu được ánh sáng vừa và thích hợp cho góc làm việc.", "Aglaonema_commutatum2.jpg", "Ánh sáng gián tiếp thấp đến trung bình; giống nhiều vân cần sáng hơn.", "Tưới khi khoảng một phần ba giá thể đã khô.", "Giá thể tơi xốp, giữ ẩm vừa và có lỗ thoát nước.", "Bón phân nhẹ mỗi 6 tuần.", "Đốm nâu trên lá", "Lá ướt lâu, bí khí hoặc nhiễm nấm.", "Tỉa lá bệnh, tránh tưới lên tán và tăng thông thoáng."],
  ["dragon-tree", "Phát Tài Núi", "Dracaena marginata", "Cây thân mảnh với tán lá dài, gọn và phù hợp không gian hiện đại có diện tích nhỏ.", "Dracaena_marginata_1.jpg", "Ánh sáng gián tiếp trung bình đến sáng.", "Để ít nhất nửa chậu khô rồi mới tưới.", "Đất trồng trong nhà thoát nước nhanh.", "Bón phân loãng mỗi 6–8 tuần vào xuân hè.", "Đầu lá cháy", "Nước nhiều khoáng, độ ẩm thấp hoặc bón dư phân.", "Dùng nước ít khoáng, tăng ẩm và giảm lượng phân."],
  ["hoya-carnosa", "Cẩm Cù", "Hoya carnosa", "Cây dây leo lá dày, có thể cho chùm hoa thơm khi nhận đủ ánh sáng và được chăm ổn định.", "Hoya_carnosa_1.jpg", "Ánh sáng gián tiếp rất sáng, có thể nhận nắng sớm.", "Tưới khi phần lớn giá thể đã khô.", "Hỗn hợp vỏ thông, perlite và xơ dừa thật thoáng.", "Bón phân loãng mỗi tháng khi cây đang phát triển.", "Không ra hoa", "Thiếu sáng, chậu quá lớn hoặc thường xuyên di chuyển cây.", "Tăng sáng từ từ, giữ vị trí ổn định và không cắt cuống hoa cũ."],
  ["cast-iron-plant", "Tỏi Rừng", "Aspidistra elatior", "Cây lá bền bỉ, chịu bóng tốt và phù hợp những vị trí ít sáng trong nhà.", "Aspidistra_elatior1.jpg", "Ánh sáng thấp đến trung bình, tránh nắng trực tiếp.", "Tưới khi 3–5 cm đất mặt khô.", "Đất giàu mùn nhưng phải thoát nước.", "Bón phân nhẹ mỗi 2 tháng vào mùa sinh trưởng.", "Lá bạc màu", "Nắng trực tiếp quá mạnh hoặc nhện đỏ.", "Dời khỏi nắng, kiểm tra mặt dưới lá và xử lý sâu hại nếu có."],
  ["calathea-orbifolia", "Đuôi Công Tròn", "Goeppertia orbifolia", "Cây lá sọc bạc nổi bật, ưa độ ẩm ổn định và môi trường tránh gió điều hòa trực tiếp.", "Calathea_orbifolia_2.jpg", "Ánh sáng gián tiếp trung bình; tránh nắng chiếu lên lá.", "Giữ đất ẩm nhẹ, tưới khi mặt đất vừa se khô.", "Giá thể giữ ẩm nhưng giàu vật liệu thoáng khí.", "Bón phân rất loãng mỗi 6 tuần.", "Mép lá quăn nâu", "Không khí khô, nước cứng hoặc đất khô quá lâu.", "Tăng ẩm, dùng nước ít khoáng và giữ ẩm ổn định hơn."],
  ["boston-fern", "Dương Xỉ Boston", "Nephrolepis exaltata", "Dương xỉ có tán mềm rủ, phù hợp phòng sáng dịu và có độ ẩm không khí khá.", "Nephrolepis_exaltata_1.jpg", "Ánh sáng gián tiếp trung bình đến sáng.", "Giữ giá thể ẩm đều nhưng không sũng nước.", "Đất giàu hữu cơ, tơi và thoát nước.", "Bón phân nửa liều mỗi 4–6 tuần.", "Lá khô rụng", "Thiếu ẩm, đất khô hoặc luồng khí nóng lạnh trực tiếp.", "Tăng độ ẩm, tưới đều và tránh đặt sát máy lạnh."],
  ["pilea-peperomioides", "Đồng Tiền Trung Quốc", "Pilea peperomioides", "Cây nhỏ có lá tròn trên cuống dài, dễ nhân giống từ cây con quanh gốc.", "Pilea_peperomioides_2017.jpg", "Ánh sáng gián tiếp sáng; xoay chậu mỗi tuần.", "Tưới khi 2–3 cm đất mặt khô.", "Giá thể nhẹ, thoát nước nhanh.", "Bón phân loãng mỗi tháng vào mùa ấm.", "Cuống dài, cây lệch", "Thiếu sáng hoặc không xoay chậu.", "Đưa cây gần nguồn sáng hơn và xoay một phần tư vòng mỗi tuần."],
  ["bird-of-paradise", "Thiên Điểu", "Strelitzia reginae", "Cây lá lớn mang phong cách nhiệt đới, cần không gian và ánh sáng mạnh để phát triển khỏe.", "Strelitzia_reginae_1.jpg", "Ánh sáng rất sáng, chịu được vài giờ nắng nhẹ sau khi thích nghi.", "Tưới khi 3–5 cm đất mặt khô.", "Đất giàu dinh dưỡng, thoát nước tốt và chậu chắc chắn.", "Bón phân cân bằng mỗi tháng vào mùa sinh trưởng.", "Lá cuộn hoặc rách", "Thiếu nước, không khí khô; rách nhẹ cũng có thể do đặc tính tự nhiên.", "Ổn định nhịp tưới, tăng ẩm và tránh luồng gió mạnh."],
  ["peperomia-obtusifolia", "Trường Sinh", "Peperomia obtusifolia", "Cây nhỏ gọn có lá dày bóng, hợp bàn làm việc và căn hộ có ánh sáng dịu.", "Peperomia_obtusifolia2.jpg", "Ánh sáng gián tiếp trung bình đến sáng.", "Để ít nhất nửa giá thể khô trước khi tưới.", "Giá thể rất thoáng, chậu nhỏ có lỗ thoát nước.", "Bón phân loãng mỗi 6–8 tuần.", "Thân mềm đen", "Tưới quá nhiều gây thối thân và rễ.", "Cắt bỏ phần hỏng, giâm phần khỏe và thay đất khô thoáng."],
  ["anthurium-andraeanum", "Hồng Môn", "Anthurium andraeanum", "Cây có mo hoa đỏ hoặc hồng nổi bật, thích môi trường ấm ẩm và ánh sáng tán xạ.", "Anthurium_andraeanum_2.jpg", "Ánh sáng gián tiếp sáng để cây ra hoa đều.", "Tưới khi 2–3 cm đất mặt khô.", "Giá thể vỏ thông, xơ dừa và perlite thoáng khí.", "Bón phân loãng mỗi 6 tuần.", "Lá có quầng vàng nâu", "Lá ướt lâu, bí khí hoặc bệnh đốm lá.", "Cách ly, tỉa lá bệnh, giữ lá khô và tăng lưu thông không khí."],
];

const additionalArticles = [
  ["GUIDE_HUMIDITY_2026", "Độ ẩm trong nhà: tăng đúng cách mà không gây nấm", "Độ ẩm phù hợp giúp nhiều cây nhiệt đới mở lá đẹp và giảm khô mép, nhưng không có nghĩa là giữ lá luôn ướt. Phần lớn cây nội thất thích không khí ẩm vừa cùng luồng khí lưu thông nhẹ.\n\nHãy ưu tiên đặt cây thành nhóm, dùng máy tạo ẩm có ẩm kế hoặc đặt cây tại phòng có độ ẩm ổn định. Khay sỏi chỉ có tác dụng trong phạm vi nhỏ và đáy chậu không được ngâm trong nước.\n\nPhun sương không thay thế việc tưới và hiệu quả tăng ẩm rất ngắn. Nếu lá ướt kéo dài vào ban đêm, nguy cơ đốm lá và nấm tăng lên.\n\nMục tiêu thực tế là môi trường ổn định: tránh luồng điều hòa thổi trực tiếp, giữ tán thông thoáng và lau lá định kỳ.", "Calathea_orbifolia_2.jpg", ["Độ ẩm","Môi trường","Nấm bệnh"]],
  ["GUIDE_SOIL_2026", "Phối giá thể thoáng cho cây trồng trong nhà", "Một giá thể tốt phải đồng thời giữ đủ ẩm và tạo khoảng trống cho rễ hô hấp. Đất quá mịn dễ nén chặt, trong khi hỗn hợp quá thô có thể khô nhanh hơn khả năng chăm sóc của bạn.\n\nXơ dừa hoặc đất hữu cơ giúp giữ ẩm; perlite, đá bọt và vỏ thông tạo độ thoáng. Tỷ lệ cần thay đổi theo loài cây, kích thước chậu và điều kiện phòng.\n\nKhi tưới mà nước nằm lâu trên mặt, đất có mùi bí hoặc chậu rất lâu khô, hãy kiểm tra độ nén và lỗ thoát nước. Không nên lót một lớp sỏi dưới đáy để chữa giá thể bí.\n\nTrộn nguyên liệu sạch, làm ẩm nhẹ trước khi dùng và tránh nén chặt quanh rễ khi thay chậu.", "Monstera_deliciosa2.jpg", ["Giá thể","Rễ cây","Thay chậu"]],
  ["GUIDE_FERTILIZER_2026", "Bón phân cho cây nội thất: ít nhưng đều", "Phân bón bổ sung dinh dưỡng chứ không chữa được thiếu sáng, úng rễ hoặc sâu bệnh. Chỉ bón khi cây đang phát triển và bộ rễ khỏe.\n\nBắt đầu với một nửa liều trên nhãn, tưới trên nền đất đã hơi ẩm và quan sát phản ứng trong những tuần tiếp theo. Cây ở nơi ít sáng thường cần phân ít hơn cây đang tăng trưởng mạnh.\n\nDấu hiệu bón quá nhiều gồm cháy mép lá, lớp muối trắng trên mặt đất và rễ tổn thương. Khi đó ngừng bón và xả giá thể bằng nước sạch nếu chậu thoát nước tốt.\n\nMùa lạnh hoặc giai đoạn cây ngừng phát triển, hãy giãn hoặc tạm dừng bón thay vì giữ lịch cố định quanh năm.", "Pilea_peperomioides_2017.jpg", ["Phân bón","Dinh dưỡng","Cơ bản"]],
  ["GUIDE_ROOT_ROT_2026", "Nhận biết và xử lý thối rễ trước khi quá muộn", "Thối rễ thường bắt đầu từ giá thể ẩm kéo dài và thiếu oxy. Lá vàng mềm, cây héo dù đất còn ướt, thân sát gốc nhũn hoặc mùi chua là những tín hiệu cần kiểm tra.\n\nNhẹ nhàng lấy cây khỏi chậu. Rễ khỏe thường chắc và sáng màu; rễ thối mềm, sẫm màu và dễ tuột lớp ngoài. Dùng kéo sạch cắt bỏ phần hỏng rồi khử trùng kéo.\n\nTrồng lại bằng giá thể mới thoáng trong chậu có lỗ thoát nước. Không chọn chậu quá lớn và không bón phân ngay sau khi xử lý.\n\nNếu bộ rễ mất quá nhiều, hãy lấy phần thân khỏe để giâm dự phòng. Sau đó điều chỉnh nhịp tưới dựa trên độ khô thực tế, không dựa vào lịch cứng.", "Peperomia_obtusifolia2.jpg", ["Thối rễ","Cấp cứu cây","Tưới nước"]],
  ["GUIDE_PRUNING_2026", "Cắt tỉa và tạo tán để cây khỏe, cân đối", "Cắt tỉa loại bỏ lá hỏng, kích thích chồi mới và giữ kích thước phù hợp với không gian. Trước khi cắt, xác định mắt lá và hình dáng bạn muốn cây phát triển.\n\nDùng kéo sắc đã khử trùng. Cắt bỏ lá vàng sát cuống nhưng không làm tổn thương thân chính; với cây dây leo, cắt ngay phía trên một mắt lá để khuyến khích phân nhánh.\n\nKhông nên loại bỏ quá nhiều tán trong một lần, đặc biệt khi cây đang yếu hoặc vừa thay chậu. Phần cắt khỏe có thể dùng để giâm nếu loài cây phù hợp.\n\nSau khi tỉa, giữ cây ở môi trường ổn định và quan sát vết cắt. Khử trùng dụng cụ trước khi chuyển sang cây khác để tránh lây bệnh.", "Philodendron_hederaceum_2005-03-14.jpg", ["Cắt tỉa","Tạo tán","Nhân giống"]],
  ["GUIDE_PROPAGATION_2026", "Nhân giống bằng cành: từ một mắt lá thành cây mới", "Nhiều cây dây leo như trầu bà và philodendron có thể nhân giống từ đoạn thân mang ít nhất một mắt lá. Mắt là điểm chồi hoặc rễ mới sẽ phát triển; một chiếc lá không có mắt thường không tạo được cây hoàn chỉnh.\n\nChọn cành khỏe, cắt bằng dụng cụ sạch ngay dưới mắt. Có thể giâm trong nước để dễ theo dõi hoặc trong giá thể ẩm thoáng để rễ thích nghi sớm hơn.\n\nĐặt cành ở nơi sáng gián tiếp, ấm và tránh thay nước toàn bộ quá thường xuyên. Khi rễ có nhiều nhánh và dài vài centimet, chuyển sang chậu nhỏ.\n\nGiữ ẩm nhẹ trong những tuần đầu nhưng không để giá thể sũng. Cây mới cần thời gian thích nghi trước khi bón phân.", "Hoya_carnosa_1.jpg", ["Nhân giống","Giâm cành","Cây dây leo"]],
  ["GUIDE_LEAF_CLEANING_2026", "Lau lá đúng cách để cây quang hợp tốt hơn", "Bụi bám trên lá làm giảm ánh sáng đến bề mặt lá và che khuất dấu hiệu sâu hại. Với cây lá lớn, lau định kỳ bằng khăn mềm ẩm là cách đơn giản và hiệu quả.\n\nĐỡ mặt dưới lá bằng một tay, lau nhẹ từ cuống ra đầu lá. Với cây nhiều lá nhỏ, có thể tắm bằng vòi nước nhẹ rồi để ráo hoàn toàn ở nơi thông thoáng.\n\nKhông cần dùng chất làm bóng lá, dầu hoặc sữa vì chúng có thể bít khí khổng và giữ bụi. Luôn kiểm tra mặt dưới lá, nách lá trong lúc vệ sinh.\n\nNếu phát hiện côn trùng hoặc đốm bất thường, cách ly cây trước khi đặt lại vào nhóm và vệ sinh khăn, dụng cụ đã sử dụng.", "Anthurium_andraeanum_2.jpg", ["Vệ sinh lá","Quang hợp","Sâu bệnh"]],
  ["GUIDE_VACATION_2026", "Chuẩn bị cây trước chuyến đi dài ngày", "Trước chuyến đi, hãy gom cây theo nhu cầu ánh sáng và kiểm tra từng chậu thay vì tưới thật nhiều một lượt. Cây chịu hạn không cần được ngâm nước chỉ vì bạn sắp vắng nhà.\n\nTưới đẫm những cây thực sự đã khô, để nước thoát hết và chuyển cây khỏi nắng gắt để giảm tốc độ mất nước. Không thay chậu hoặc bón phân ngay trước ngày đi.\n\nVới chuyến đi dài, hệ thống dây thấm hoặc người chăm hộ cần được thử trước vài ngày. Ghi nhãn rõ cây nào chỉ tưới khi khô và cây nào cần ẩm đều.\n\nKhi trở về, kiểm tra đất và rễ trước khi tưới. Xử lý từng cây theo tình trạng thực tế thay vì bù nước hàng loạt.", "Aspidistra_elatior1.jpg", ["Du lịch","Tưới nước","Lập kế hoạch"]],
  ["GUIDE_PET_SAFETY_2026", "Bố trí cây an toàn khi nhà có chó mèo", "Một số cây nội thất có thể gây kích ứng hoặc ngộ độc nếu thú cưng nhai phải. Trước khi mua cây, hãy tra cứu tên khoa học từ nguồn thú y đáng tin cậy vì tên phổ thông có thể gây nhầm lẫn.\n\nĐặt cây ngoài tầm với không phải lúc nào cũng đủ, đặc biệt với mèo có thể leo cao. Tủ kính thoáng, phòng riêng hoặc lựa chọn loài được xem là an toàn là giải pháp bền vững hơn.\n\nThu gom lá rụng, không để nước có pha phân bón trong đĩa và cất thuốc xử lý sâu bệnh kín. Nếu thú cưng đã nhai cây, giữ lại ảnh hoặc mẫu cây để hỗ trợ nhận diện.\n\nKhi có nôn, chảy dãi, khó thở hoặc biểu hiện bất thường, liên hệ bác sĩ thú y ngay thay vì tự điều trị tại nhà.", "Nephrolepis_exaltata_1.jpg", ["Thú cưng","An toàn","Bố trí cây"]],
  ["GUIDE_SEASONAL_CARE_2026", "Điều chỉnh chăm cây theo mùa và thời tiết", "Nhu cầu nước của cây thay đổi theo ánh sáng, nhiệt độ, độ ẩm và tốc độ sinh trưởng. Vì vậy cùng một chậu cây có thể khô sau bốn ngày vào mùa nóng nhưng cần hơn một tuần trong thời tiết mát.\n\nMùa mưa hoặc ngày âm u, giảm tần suất tưới và tăng lưu thông không khí. Mùa nóng, kiểm tra cây thường xuyên hơn nhưng vẫn chỉ tưới khi giá thể đạt độ khô phù hợp.\n\nKhi dùng điều hòa, tránh đặt cây ngay luồng gió lạnh. Những đợt thay đổi thời tiết mạnh cũng không phải thời điểm tốt để thay chậu hoặc bón phân đậm.\n\nGhi lại ngày tưới và phản ứng của cây trong vài tuần sẽ giúp bạn xây dựng nhịp chăm theo chính căn phòng của mình.", "Strelitzia_reginae_1.jpg", ["Theo mùa","Thời tiết","Lịch chăm"]],
];

const imageAliases = {
  "Philodendron_hederaceum_2005-03-14.jpg": "Philodendron_hederaceum_kz02.jpg",
  "Dracaena_marginata_1.jpg": "Dracaena_marginata_IndoorPlant_0605k.jpg",
  "Nephrolepis_exaltata_1.jpg": "Nephrolepis_exaltata_indoor0705c.jpg",
  "Pilea_peperomioides_2017.jpg": "Pilea_Peperomioides.jpg",
};
const commonsImage = fileName => `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(imageAliases[fileName] || fileName)}?width=960`;
for (const [id,name,scientificName,description,imageFile,light,water,soil,fertilizer,issue,cause,treatment] of additionalPlants)
  documents.push(["sample_plants", id, {name,scientificName,description,imageUrl:commonsImage(imageFile),createdAt:at("2026-10-02T03:00:00Z"),care:{light,water,soil,fertilizer},diseases:[{issue,cause,treatment}]}]);
additionalArticles.forEach(([id,title,content,imageFile,tags], index) =>
  documents.push(["articles", id, {title,content,coverImage:commonsImage(imageFile),tags,views:0,createdAt:at(`2026-10-02T04:${String(index).padStart(2,"0")}:00Z`)}]));

const defaultImage = "https://i.ibb.co/MkMj38WM/plant.png";
const imageUpdates = [
  ["3tH705XSq7pl7YjSL5bX", "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ad/Epipremnum_aureum_kz01.jpg/960px-Epipremnum_aureum_kz01.jpg"],
  ["8xUYQAeubZiLInNu4seC", "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b5/Aloe_vera_Lanzarote.jpg/960px-Aloe_vera_Lanzarote.jpg"],
  ["DYkOb3q54mjsJX1rS2ie", "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a9/Asparagales_-_Sansevieria_trifasciata_4.jpg/960px-Asparagales_-_Sansevieria_trifasciata_4.jpg"],
  ["LSbmzQf9e93wa4gjJvD0", "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b9/Zamioculcas_zamiifolia_Chameleon_1.jpg/960px-Zamioculcas_zamiifolia_Chameleon_1.jpg"],
  ["YRuFlTdtxTec2CQdwvO8", "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d7/Chamaedorea_elegans07ra.jpg/960px-Chamaedorea_elegans07ra.jpg"],
  ["a4G13c9Z8RIZU47nTUz6", "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e2/%D8%A8%D8%B1%DA%AF_%D9%88_%D8%B3%D8%A7%D9%82%D9%87_%DA%AF%DB%8C%D8%A7%D9%87_%D8%B9%D9%86%DA%A9%D8%A8%D9%88%D8%AA%DB%8C_04-Chlorophytum_comosum%2C.jpg/960px-%D8%A8%D8%B1%DA%AF_%D9%88_%D8%B3%D8%A7%D9%82%D9%87_%DA%AF%DB%8C%D8%A7%D9%87_%D8%B9%D9%86%DA%A9%D8%A8%D9%88%D8%AA%DB%8C_04-Chlorophytum_comosum%2C.jpg"],
  ["jtBjBcZAA2Z3wDtxRvOW", "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a1/Peace_lily_-_2.jpg/960px-Peace_lily_-_2.jpg"],
  ["tMGgJEBUczYMd3foJ2sk", "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Ficus_lyrata_393081802.jpg/960px-Ficus_lyrata_393081802.jpg"],
];

async function main(args) {
  const allowed = new Set(["--dry-run", "--apply", confirm]);
  if (args.some(arg => !allowed.has(arg))) throw new Error("Unknown argument");
  const apply = args.includes("--apply");
  if (apply && !args.includes(confirm)) throw new Error(`Writes require --apply ${confirm}`);
  const keyPath = process.env.PRODUCTION_FIREBASE_KEY_PATH;
  if (!keyPath) throw new Error("Set PRODUCTION_FIREBASE_KEY_PATH");
  const key = JSON.parse(fs.readFileSync(path.resolve(keyPath), "utf8"));
  if (key.project_id !== TARGET_PROJECT) throw new Error("Credential project mismatch");
  const app = initializeApp({credential:cert(key),projectId:TARGET_PROJECT}, "curated-content-seed");
  try {
    const db = getFirestore(app); const result=[];
    for (const [collection,id,data] of documents) {
      const ref=db.collection(collection).doc(id); const existing=await ref.get();
      if (existing.exists) { result.push({collection,id,action:"skip"}); continue; }
      if (apply) await ref.create(data);
      result.push({collection,id,action:apply?"created":"pending"});
    }
    for (const [id,imageUrl] of imageUpdates) {
      const ref=db.collection("sample_plants").doc(id); const snapshot=await ref.get();
      if (!snapshot.exists) { result.push({collection:"sample_plants",id,action:"missing"}); continue; }
      if (snapshot.data().imageUrl !== defaultImage) { result.push({collection:"sample_plants",id,action:"preserved"}); continue; }
      if (apply) await ref.update({imageUrl});
      result.push({collection:"sample_plants",id,action:apply?"image-updated":"image-pending"});
    }
    console.log(JSON.stringify({project:TARGET_PROJECT,mode:apply?"apply":"dry-run",documents:result},null,2));
  } finally { await deleteApp(app); }
}

module.exports={documents,imageUpdates,main};
if(require.main===module)main(process.argv.slice(2)).catch(error=>{console.error(error.message);process.exitCode=1;});
